### ISSUE TITLE
Identify type of Markdown item as part of AST?

### ISSUE THREAD

**Issue by gjtorikian** [commonmark/cmark#125]
I noticed that, given different types of lists, the AST renders the precise same way. ([Example](http://spec.commonmark.org/dingus/?text=*%20word%0A*%20hey%0A%0A-%20hey%0A-%20word%0A%0A))

That is, given:

``` markdown
* word
* hey

- hey
- word
```

The AST lists

```
<list type="bullet" tight="true">
```

for both types of lists. I would hope that it had mentioned `asterisk` or `dash` or something.

@jgm Is there a reason for this? And if not, would you accept a contribution to fix that?

**Comment by jgm** [comment]
I'm not sure about this one. See the discussion at
http://talk.commonmark.org/t/preserve-bullet-char-in-ast/1108
It would be helpful if you'd comment there on the discussion
so far, and say a bit about why you'd like this feature.

+++ Garen Torikian [May 12 16 14:53 ]:

**Comment by jgm** [comment]
To do this, we'd need to extend the API with something like `cmark_node_get_list_bullet` or something like that.

Here's one potential issue I see:  suppose we have an HTML -> CommonMark converter (I've written one of these using my lua bindings).  If we add bullet types to the AST, then when we're building the AST to match the structure of the HTML document, we need to specify a bullet type of `*`, `+`, or `-` for each unordered list.  But of course, there's nothing corresponding to that in HTML.

Perhaps this is just a minor inconvenience, since you could set this arbitrarily or leave it as its default value.

I'd be receptive to a PR to add this feature, if you need it in github.
