### ISSUE TITLE
Is there a way to not escape exclamation marks?

### ISSUE THREAD

**Issue by joneshf** [commonmark/cmark#266]
Hi, I'm running into an issue with some markdown.

If I have a string like `"Hello!"`, and render it as Commonmark, it is rendered as `"Hello\!"`. It looks like wxclamation marks are escaped when rendering to Commonmark, but not when rendering to anything else (like HTML). I've tried looking in the spec for where this is a requirement, but couldn't find anything. Is the escaping a required part of the spec?

Is there a way to not escape the exclamation marks? It looks like this condition is what's causing them to be escaped: https://github.com/commonmark/cmark/blob/63c675f9acead1171a2881fbbf12ddc6c3cc82d1/src/commonmark.c#L36

Is that right?

**Comment by jgm** [comment]
cmark's commonmark renderer escapes all !s, because
otherwise a literal '!' followed by literal text
in square brackets could come out as a commonmark
image.

There's no way to disable this.

The spec says that ! is backslash-escapable.  The
backslash is always possible before a literal !.
It's only sometimes necessary.  Rather than trying
to determine when it is necessary, the commonmark
writer just always escapes it.  It could be improved
by having it look for a following `[`.

**Comment by joneshf** [comment]
> It could be improved by having it look for a following `[`.

Would you accept a PR to do that?

**Comment by jgm** [comment]
I'd consider one.  There might be problems I can't
think of now.
