### ISSUE TITLE
Quadratic behaviour on pathological html

### ISSUE THREAD

**Issue by marcusklaas** [commonmark/cmark#299]
Found [this vulnerability](https://github.com/raphlinus/pulldown-cmark/issues/280) in pulldown-cmark and md4c. It appears cmark is also vulnerable.

```bash
python -c 'print("a <![CDATA[" * 10000)' | time cmark > /dev/null
0.40user 0.00system 0:00.42elapsed 95%CPU (0avgtext+0avgdata 9720maxresident)k

python -c 'print("a <![CDATA[" * 20000)' | time cmark > /dev/null
1.60user 0.00system 0:01.62elapsed 98%CPU (0avgtext+0avgdata 17760maxresident)k

python -c 'print("a <![CDATA[" * 40000)' | time cmark > /dev/null
6.20user 0.02system 0:06.25elapsed 99%CPU (0avgtext+0avgdata 34372maxresident)k
```

**Comment by jgm** [comment]
Thanks!

**Comment by jgm** [comment]
This has to do with parsing of CDATA elements as inline HTML, not HTML blocks.  And this is handled entirely by a scanner defined using re2c, which works in linear time.  However, in this case the linear-time parser gets applied repeatedly to the tail of the input string.

It's tricky because, while with regular tags we can quit parsing when we hit `<`, with CDATA, we need to keep parsing when we hit `<![CDATA[`, because this can occur within a CDATA element.

I guess we'll need to special-case CDATA somehow, keeping track of the last position we've failed to find `]]>`.

**Comment by marcusklaas** [comment]
I came to a similar conclusion. Maybe simply setting a flag would be enough? If we fail to find `]]>` once, I think we will never find it after.

**Comment by mity** [comment]
cmark is also vulnerable to 

```
time python -c 'print("a" + "<!A" * 40000)'
```

It's likely the same story as it was in MD4C.

**Comment by mity** [comment]
And also to 

```
time python -c 'print("a" + "<?" * 40000)' | ./src/cmark >/dev/null
```

**Comment by jgm** [comment]
Also
```
time python -c 'print("a <!A " * 40000)' | time cmark > /dev/null
```

**Comment by jgm** [comment]
I think that, instead of handling these with the regex, we need a manual scanner that can keep track of where it failed.

**Comment by nwellnhof** [comment]
Also found by OSS-Fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32344

Possible fix: Don't try to reparse these constructs if the (fixed) character sequence required to terminate them wasn't found during the first scan.

**Comment by nwellnhof** [comment]
Proposed fix: https://github.com/nwellnhof/cmark/commit/1944fe7abe761bff0c082a083692c8f54df24611

**Comment by jgm** [comment]
@nwellnhof I haven't had a chance to really look in detail, but the idea looks good to me on first glance; do you want to submit a PR?
