### ISSUE TITLE
Issue revealed by fuzzer

### ISSUE THREAD

**Issue by jgm** [commonmark/cmark#355]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21035#c2

oss-fuzz issue 21035
Crash State:
  cmark_strbuf_putc
  cmark_render_xml
  cmark-fuzz.c

**Comment by jgm** [comment]
Great, I didn't know about this.  Please do go ahead with a PR.

I'll leave this issue open as a suggestion to disable indenting in XML after a certain depth is reached.

**Comment by nwellnhof** [comment]
If we don't limit the indent level, we have to limit the input size for fuzzing further to something around 10KB. So can we first add the indent limit? This is basically a DoS attack against the XML renderer which should be fixed in any case. I also see no practical reason to produce XML files with lines indented by hundreds of spaces.

**Comment by nwellnhof** [comment]
This should be fixed now.
